let age;
console.log (typeof age); 
let num = 20;
console.log (typeof num);
let cif = 1234569n;
console.log (typeof cif); 
let str = 'Привет';
console.log (typeof str); 
let TF = true;
console.log (typeof TF); 
let sim = Symbol();
console.log (typeof sim); 
let user = {age:30};
console.log (typeof user);
let per = null;
console.log (typeof per); 
let us = function(){};
console.log (typeof us); 